from . import hr_employee_extra_input
from . import hr_contract
from . import mail_activity
from . import hr_payslip_day
from . import hr_payslip
from . import hr_leave_type
from . import hr_department
from . import jic_hr_overtime
from . import hr_leave