from . import hr_employee_emergency
from . import hr_employee_qualification
from . import hr_employee_dependent
from . import jic_project_task
from . import jic_project_timesheet
from . import jic_hr_employee
from . import hr_employee_grade
from . import res_company
from . import hr_department
