# -*- coding: utf-8 -*-

{
    'name': 'Odoo 15 Base Module for Jobin International Company',
    'version': '15.0.1.0.0',
    'category': 'General',
    'description': 'Base Module for JIC IT projects ',
    'summary': 'Essential module for work with JIC Projects',
    'sequence': '1',
    'author': 'JIC IT Solutions',
    'license': 'LGPL-3',
    'company': 'JIC IT Solutions',
    'maintainer': 'JIC',
    'support': 'jic@gmail.com',
    'website': 'https://www.jic.com',
    'depends': ['web', 'hr', 'hr_recruitment','hr_skills', 'web_responsive', 'hr_payroll_community','fims_login_background_and_styles'],
    'live_test_url': '',
    'data': ['security/ir.model.access.csv',
             'security/hr_dashboard_security.xml',
             'views/dashboard_action.xml',
             'views/dashboard_menu_description.xml',
             'views/job_description_view.xml',
             ],
    'assets': {
        'web.assets_backend': [
            '/mena_hr_dashboard/static/src/js/dashboard.js',
            '/mena_hr_dashboard/static/src/js/hr_dashboard.js',
            '/mena_hr_dashboard/static/src/css/dashboard.css',
            "/mena_hr_dashboard/static/src/components/apps_menu/apps_menu_inherit.scss",
            # "/mena_hr_dashboard/static/src/components/apps_menu/inherit_apps_menu.esm.js",
            "/mena_hr_dashboard/static/src/components/navbar/main_navbar.scss",
        ],
        'web.assets_qweb': [
                '/mena_hr_dashboard/static/src/xml/dashboard.xml',
                '/mena_hr_dashboard/static/src/xml/hr_dashboard.xml',
                '/mena_hr_dashboard/static/src/components/apps_menu/apps_menu_inherit.xml',
            ],
    },
    'pre_init_hook': '',
    'installable': True,
    'application': False,
    'auto_install': False,
    'images': [],
}
